# Generated by Django 6.0.1 on 2026-02-25 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_keyword_comment_package_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebuild',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=127)),
                ('content', models.TextField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.package')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
